ТЗ-9
yrMajesty/java-filmorate pull request #4
Opened 2023-04-04 18:44 UTC by yrMajesty

2023-04-05 12:25 UTC, TomattmanYandex requested changes
Все еще что то странно с репозиторием. но уже приемлимо
комменты в пулл реквесте

2023-04-05 12:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/config/SpringConfig.java
> +@ComponentScan("ru.yandex.practicum.filmorate")
это не обязательно, аннотация @SpringBootApplication уже содержит эту аннотацию и автоматически просканирует все пакеты которые находятся ниже ее уровня

2023-04-05 12:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/config/SpringConfig.java
> +    @Bean
это тоже можно удалить а на классы репозитория повесить аннотацию @Component

2023-04-05 12:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/config/SpringConfig.java
> +}
Этот класс вообще не нужен, все что в нем есть можно и нужно з исполнить по другому

2023-04-05 12:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
так как мы используем Lombook то лучше использовать аннотацию @RequiredArgsConstructor так при появлении новых зависимостей не надо будет изменять конструктор все сделается автоматически

2023-04-05 12:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film updateFilm(@RequestBody Film film) {
тут тоже должна быть проверка валидации

2023-04-05 12:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
тут все то же самое что и в классе выше

2023-04-05 12:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/exception/NoSuchFilmException.java
> +public class NoSuchFilmException extends RuntimeException {
этот и следующий класс одинаковые, не лучше ли создать одну универсальную ошибку, которая будет работать со всеми обьектами?

2023-04-05 12:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info("Request add new user");
не хватает логики проставления имени одинакового с логином если необходимо

2023-04-05 12:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Null
стоит убрать это проверку валидации, так как при обновлении надо валидировать тоже, а там уже может быть не null

2023-04-05 12:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Long id;
Аналогично с предыдущим

2023-04-05 12:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +public class FilmRepository {
стоит добавить аннотацию @Component и не нужно будет инициализировать через конфиг

2023-04-05 12:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +    private final Map<Long, Film> films = new HashMap<>();
круто что уже сделан отдельный класс репозитория ( хотя этого пока и не надо было)

2023-04-05 17:47 UTC, yrMajesty commented
Александр, спасибо за правки, можно уточнить, что не так с моим репозиторием?

2023-04-05 17:48 UTC, yrMajesty commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info("Request add new user");
Эта логика -  если отсутствует имя, устанавливается значение логина, описана в методе класса UserRepository.
        if (user.getName() == null || user.getName().isEmpty()) {
            user.setName(user.getLogin());
        }

2023-04-06 15:02 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info("Request add new user");
отлично, но в следующем спринте, когда будет добавлен слой сервисов, это логика должна будет быть в нем

2023-04-15 14:42 UTC, merged